website:
  description: "Blog du r√©seau des data scientists de la statistique publique"
  navbar:
    search: true
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/InseeFrLab/ssphub
    left:
      - href: index.qmd
        text: "Accueil"
      - href: event.qmd
        text: "√âv√©nements"
      - href: blog.qmd
        text: "Blog"
      - href: project.qmd
        text: "Projets"
      - href: course.qmd
        text: "Ressources utiles"
      - text: "√Ä propos"
        menu:
          - href: infolettre/infolettre.qmd
            text: "Newsletters"
          - href: about.qmd
            text: "Pr√©sentation du r√©seau"
          - href: manifeste.qmd
            text: "Manifeste du r√©seau"
      - href: https://datalab.sspcloud.fr/
        text: "Le SSPCloud"

  announcement:
    icon: bi-megaphone
    dismissable: true
    content: "üì∫Ô∏è Les pr√©sentations et le replay de la journ√©e du r√©seau, le 1^er^ d√©cembre 2025, [sont disponibles](/event/2025-12-01-network-day/index.qmd)"
    type: primary
    position: below-navbar

lang: fr
