website:
  description: "Network of data scientists working for the French administration"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/InseeFrLab/ssphub
    left:
      - href: index.qmd
        text: "Home"
      - href: project.qmd
        text: "Innovative projects"
      - href: about.qmd
        text: "About the SSPHub"
      - href: https://datalab.sspcloud.fr/
        text: "SSPCloud"

lang: en-GB
