# Workflow run only on pushes to main and manual trigger
on:
  workflow_dispatch:
  # cf https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  push:
    branches: main

name: CI - Quarto Publish

# Cancel previous workflow of ci that could be running
concurrency:
  group: ci-${{ github.ref }}  # preview followed by the reference of the branch or tag that triggered the workflow
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: pip install jupyter nbformat
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.31

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}


